# Generated by Django 6.0.3 on 2026-03-27 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_key', models.CharField(editable=False, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time_utc', models.TimeField()),
                ('length_seconds', models.PositiveIntegerField()),
                ('car', models.CharField(blank=True, max_length=255)),
                ('track', models.CharField(blank=True, max_length=255)),
                ('setup', models.TextField(blank=True)),
                ('fuel_capacity', models.FloatField(blank=True, null=True)),
                ('fuel_per_lap', models.FloatField(blank=True, null=True)),
                ('tire_change_fuel_min', models.FloatField(blank=True, null=True)),
                ('target_laps', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_lap_seconds', models.FloatField(blank=True, null=True)),
                ('in_lap_seconds', models.FloatField(blank=True, null=True)),
                ('out_lap_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_utc', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='events.driver')),
            ],
            options={
                'ordering': ['slot_utc'],
                'unique_together': {('driver', 'slot_utc')},
            },
        ),
        migrations.CreateModel(
            name='StintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stint_number', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stint_assignments', to='events.driver')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stint_assignments', to='events.event')),
            ],
            options={
                'ordering': ['stint_number'],
                'unique_together': {('event', 'stint_number')},
            },
        ),
    ]
