# Generated by Django 6.0.3 on 2026-04-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_admin_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
