# Generated by Django 6.0.3 on 2026-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_availability_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
