# Generated by Django 6.0.3 on 2026-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recruiting',
            field=models.BooleanField(default=False),
        ),
    ]
