# Generated by Django 6.0.3 on 2026-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_game_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='race_start_time_utc',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
