# Generated by Django 6.0.3 on 2026-04-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ip_address',
        ),
    ]
