# Generated by Django 6.0.3 on 2026-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_driver_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='stintassignment',
            name='condition',
            field=models.CharField(choices=[('dry', 'Dry'), ('mixed', 'Mixed'), ('wet', 'Wet')], default='dry', max_length=10),
        ),
    ]
