# Generated by Django 6.0.3 on 2026-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_stint_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stintassignment',
            name='actual_start_utc',
            field=models.DateTimeField(blank=True, help_text='Manual override for stint start time. When set, this and all subsequent stints cascade from this time.', null=True),
        ),
    ]
