# Generated by Django 6.0.3 on 2026-08-19 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_realign_availability_to_half_hour_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='request_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('event_id_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('is_htmx', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['action', '-occurred_at'], name='activity_action_time_idx'), models.Index(fields=['visitor_id', '-occurred_at'], name='activity_visitor_time_idx')],
            },
        ),
    ]
